M48
; DRILL file {KiCad 6.99.0-unknown-f8b157a1fb~149~ubuntu22.04.1} date jue 25 ago 2022 07:21:55
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-25T07:21:55+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.99.0-unknown-f8b157a1fb~149~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X3.1099Y-1.7205
X3.1099Y-4.126
T2
X5.9Y-1.72
X5.9Y-5.3
T0
M30
