M48
; DRILL file {KiCad 7.99.0-unknown-9f10c142c4~166~ubuntu22.04.1} date vie 17 feb 2023 16:36:40
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T16:36:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-unknown-9f10c142c4~166~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
%
G90
G05
T1
X3.1099Y-1.7205
X3.1099Y-4.126
T0
M30
