M48
; DRILL file {KiCad 7.99.0-unknown-e60837ec95~170~ubuntu22.04.1} date jue 16 mar 2023 09:30:37
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-16T09:30:37+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-unknown-e60837ec95~170~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
%
G90
G05
T1
X3.1099Y-1.7205
X3.1099Y-4.126
T0
M30
